version: '3.8'

services:
  skatepark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skatepark
    restart: unless-stopped
    env_file:
      - .env
    command: ['npm', 'start']
    volumes:
      - ./logs/skatepark:/app/logs
    ports:
      - '3002:3002'
